### ISSUE TITLE
suppose/expect

### ISSUE THREAD

**Issue by stevenvachon** [enquirer/prompt-base#9] opened 2017-07-11 06:02 UTC
It'd be great if this library could work with [suppose](https://npmjs.com/suppose). Unfortunately, it has errors with [window-size](https://npmjs.com/window-size).

**Comment by jonschlinkert** [comment] 2017-07-11 09:33
Hi @stevenvachon, closing since there is no detail at all about the actual issue.

For starters, is there a bug in prompt-base, window-size or suppose? What is suppose? It looks relatively new or at least not widely used. What exactly should be working that doesn't? Have you made certain that the issue is in this library? Was there a stack trace? What OS are you on? What version of node.js? What is "expect"? (the test assertion library? if so, what does it have to do with this?).

Feel free to create a new issue with the necessary information.

**Closed as completed by jonschlinkert** 2017-07-11 09:33 UTC

**Comment by stevenvachon** [comment] 2017-07-11 13:56
> [Expect](https://en.wikipedia.org/wiki/Expect) is a program to automate interactions with programs that expose a text terminal interface.

I wish to use [suppose](https://npmjs.com/suppose) (a Node.js implementation of `expect`) to test Enquirer prompts. Because it is a test suite, I am not piping to a TTY and am running into https://github.com/enquirer/readline-utils/issues/4

**Comment by stevenvachon** [comment] 2017-07-11 19:30
https://github.com/enquirer/readline-utils/issues/4
