### ISSUE TITLE
Periods don't get displayed.

### ISSUE THREAD

**Issue by heathgr** [enquirer/prompt-base#4] opened 2017-03-06 21:41 UTC
When running a prompt, periods don't get displayed when they are typed.  If you type "." you'll see nothing.  If you type "a", then the period will suddenly display and the prompt will read ".a".

**Comment by doowb** [comment] 2017-03-06 22:53
@heathgr I'm looking into this now.

**Comment by doowb** [comment] 2017-03-06 23:40
@heathgr [this PR](https://github.com/enquirer/readline-utils/pull/1) should fix the problem. We'll get that published soon, then you can re-install `prompt-base` to get the latest.

**Comment by heathgr** [comment] 2017-03-06 23:46
Wow, that was quick.  I'll keep an eye out for the update.  Thanks for your help @doowb!!!!

**Comment by doowb** [comment] 2017-03-07 01:24
This has been fixed in `readline-utils@0.1.4`. You can re-install to get the latest. I'll close this issue now, but if the problem is still happening, feel free to reopen. If you find another bug, please open a new issue.

**Closed as completed by doowb** 2017-03-07 01:24 UTC
